/*******************************************************************************
 * Copyright (c) 2012 HealthCare It, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the BSD 3-Clause license
 * which accompanies this distribution, and is available at
 * http://directory.fsf.org/wiki/License:BSD_3Clause
 * 
 * Contributors:
 *     HealthCare It, Inc - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 12:38:39 PM EDT 
//


package com.healthcit.cacure.export.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="form" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cadsrPublicId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="cadsrVersion" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="cadsrCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="modifiedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="questionElement" type="{}questionElementType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="tableElement" type="{}tableElementType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="linkElement" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="sourceElement">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice>
 *                                       &lt;element name="questionElement" type="{}questionElementType"/>
 *                                       &lt;element name="tableElement" type="{}tableElementType"/>
 *                                     &lt;/choice>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="learnMore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="skipRule" type="{}skipRuleType" minOccurs="0"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="isRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="externalQuestionElement" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}questionElementType">
 *                           &lt;attribute name="externalLinkId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="externalSource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="externalUuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="content" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="skipRule" type="{}skipRuleType" minOccurs="0"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="displayStyle" default="HEADING">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="CUSTOM"/>
 *                                 &lt;enumeration value="REGULAR"/>
 *                                 &lt;enumeration value="SUBHEADING"/>
 *                                 &lt;enumeration value="HEADING"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *                           &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="module" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="section" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="skipRule" type="{}skipRuleType"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="moduleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="completionTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="showPleaseSelectOptionInDropDown" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="insertCheckAllThatApplyForMultiSelectAnswers" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "form",
    "module"
})
@XmlRootElement(name = "cure")
public class Cure {

    @XmlElement(required = true)
    protected List<Cure.Form> form;
    protected List<Cure.Module> module;

    /**
     * Gets the value of the form property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the form property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cure.Form }
     * 
     * 
     */
    public List<Cure.Form> getForm() {
        if (form == null) {
            form = new ArrayList<Cure.Form>();
        }
        return this.form;
    }

    /**
     * Gets the value of the module property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the module property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Cure.Module }
     * 
     * 
     */
    public List<Cure.Module> getModule() {
        if (module == null) {
            module = new ArrayList<Cure.Module>();
        }
        return this.module;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cadsrPublicId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="cadsrVersion" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="cadsrCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="createdBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="modifiedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="questionElement" type="{}questionElementType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="tableElement" type="{}tableElementType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="linkElement" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="sourceElement">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice>
     *                             &lt;element name="questionElement" type="{}questionElementType"/>
     *                             &lt;element name="tableElement" type="{}tableElementType"/>
     *                           &lt;/choice>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="learnMore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="skipRule" type="{}skipRuleType" minOccurs="0"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="isRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="externalQuestionElement" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}questionElementType">
     *                 &lt;attribute name="externalLinkId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="externalSource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="externalUuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="content" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="skipRule" type="{}skipRuleType" minOccurs="0"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="displayStyle" default="HEADING">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="CUSTOM"/>
     *                       &lt;enumeration value="REGULAR"/>
     *                       &lt;enumeration value="SUBHEADING"/>
     *                       &lt;enumeration value="HEADING"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *                 &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "cadsrPublicId",
        "cadsrVersion",
        "cadsrCategory",
        "createdBy",
        "modifiedBy",
        "questionElement",
        "tableElement",
        "linkElement",
        "externalQuestionElement",
        "content"
    })
    public static class Form {

        @XmlElement(required = true)
        protected String name;
        protected Integer cadsrPublicId;
        protected BigDecimal cadsrVersion;
        protected String cadsrCategory;
        protected String createdBy;
        protected String modifiedBy;
        protected List<QuestionElementType> questionElement;
        protected List<TableElementType> tableElement;
        protected List<Cure.Form.LinkElement> linkElement;
        protected List<Cure.Form.ExternalQuestionElement> externalQuestionElement;
        protected List<Cure.Form.Content> content;
        @XmlAttribute(required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the cadsrPublicId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCadsrPublicId() {
            return cadsrPublicId;
        }

        /**
         * Sets the value of the cadsrPublicId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCadsrPublicId(Integer value) {
            this.cadsrPublicId = value;
        }

        /**
         * Gets the value of the cadsrVersion property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCadsrVersion() {
            return cadsrVersion;
        }

        /**
         * Sets the value of the cadsrVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCadsrVersion(BigDecimal value) {
            this.cadsrVersion = value;
        }

        /**
         * Gets the value of the cadsrCategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCadsrCategory() {
            return cadsrCategory;
        }

        /**
         * Sets the value of the cadsrCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCadsrCategory(String value) {
            this.cadsrCategory = value;
        }

        /**
         * Gets the value of the createdBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCreatedBy() {
            return createdBy;
        }

        /**
         * Sets the value of the createdBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCreatedBy(String value) {
            this.createdBy = value;
        }

        /**
         * Gets the value of the modifiedBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModifiedBy() {
            return modifiedBy;
        }

        /**
         * Sets the value of the modifiedBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModifiedBy(String value) {
            this.modifiedBy = value;
        }

        /**
         * Gets the value of the questionElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the questionElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQuestionElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link QuestionElementType }
         * 
         * 
         */
        public List<QuestionElementType> getQuestionElement() {
            if (questionElement == null) {
                questionElement = new ArrayList<QuestionElementType>();
            }
            return this.questionElement;
        }

        /**
         * Gets the value of the tableElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tableElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTableElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TableElementType }
         * 
         * 
         */
        public List<TableElementType> getTableElement() {
            if (tableElement == null) {
                tableElement = new ArrayList<TableElementType>();
            }
            return this.tableElement;
        }

        /**
         * Gets the value of the linkElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the linkElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLinkElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Cure.Form.LinkElement }
         * 
         * 
         */
        public List<Cure.Form.LinkElement> getLinkElement() {
            if (linkElement == null) {
                linkElement = new ArrayList<Cure.Form.LinkElement>();
            }
            return this.linkElement;
        }

        /**
         * Gets the value of the externalQuestionElement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the externalQuestionElement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExternalQuestionElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Cure.Form.ExternalQuestionElement }
         * 
         * 
         */
        public List<Cure.Form.ExternalQuestionElement> getExternalQuestionElement() {
            if (externalQuestionElement == null) {
                externalQuestionElement = new ArrayList<Cure.Form.ExternalQuestionElement>();
            }
            return this.externalQuestionElement;
        }

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Cure.Form.Content }
         * 
         * 
         */
        public List<Cure.Form.Content> getContent() {
            if (content == null) {
                content = new ArrayList<Cure.Form.Content>();
            }
            return this.content;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="skipRule" type="{}skipRuleType" minOccurs="0"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="displayStyle" default="HEADING">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="CUSTOM"/>
         *             &lt;enumeration value="REGULAR"/>
         *             &lt;enumeration value="SUBHEADING"/>
         *             &lt;enumeration value="HEADING"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "skipRule",
            "description"
        })
        public static class Content {

            protected SkipRuleType skipRule;
            @XmlElement(required = true)
            protected String description;
            @XmlAttribute
            protected String displayStyle;
            @XmlAttribute(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String uuid;
            @XmlAttribute(required = true)
            protected int order;

            /**
             * Gets the value of the skipRule property.
             * 
             * @return
             *     possible object is
             *     {@link SkipRuleType }
             *     
             */
            public SkipRuleType getSkipRule() {
                return skipRule;
            }

            /**
             * Sets the value of the skipRule property.
             * 
             * @param value
             *     allowed object is
             *     {@link SkipRuleType }
             *     
             */
            public void setSkipRule(SkipRuleType value) {
                this.skipRule = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the displayStyle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayStyle() {
                if (displayStyle == null) {
                    return "HEADING";
                } else {
                    return displayStyle;
                }
            }

            /**
             * Sets the value of the displayStyle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisplayStyle(String value) {
                this.displayStyle = value;
            }

            /**
             * Gets the value of the uuid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUuid() {
                return uuid;
            }

            /**
             * Sets the value of the uuid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUuid(String value) {
                this.uuid = value;
            }

            /**
             * Gets the value of the order property.
             * 
             */
            public int getOrder() {
                return order;
            }

            /**
             * Sets the value of the order property.
             * 
             */
            public void setOrder(int value) {
                this.order = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}questionElementType">
         *       &lt;attribute name="externalLinkId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="externalSource" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="externalUuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ExternalQuestionElement
            extends QuestionElementType
        {

            @XmlAttribute(required = true)
            protected String externalLinkId;
            @XmlAttribute(required = true)
            protected String externalSource;
            @XmlAttribute(required = true)
            protected String externalUuid;

            /**
             * Gets the value of the externalLinkId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExternalLinkId() {
                return externalLinkId;
            }

            /**
             * Sets the value of the externalLinkId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExternalLinkId(String value) {
                this.externalLinkId = value;
            }

            /**
             * Gets the value of the externalSource property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExternalSource() {
                return externalSource;
            }

            /**
             * Sets the value of the externalSource property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExternalSource(String value) {
                this.externalSource = value;
            }

            /**
             * Gets the value of the externalUuid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExternalUuid() {
                return externalUuid;
            }

            /**
             * Sets the value of the externalUuid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExternalUuid(String value) {
                this.externalUuid = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="sourceElement">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice>
         *                   &lt;element name="questionElement" type="{}questionElementType"/>
         *                   &lt;element name="tableElement" type="{}tableElementType"/>
         *                 &lt;/choice>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="learnMore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="skipRule" type="{}skipRuleType" minOccurs="0"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
         *       &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="isRequired" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sourceElement",
            "learnMore",
            "skipRule",
            "description"
        })
        public static class LinkElement {

            @XmlElement(required = true)
            protected Cure.Form.LinkElement.SourceElement sourceElement;
            protected String learnMore;
            protected SkipRuleType skipRule;
            @XmlElement(required = true)
            protected String description;
            @XmlAttribute(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            protected String uuid;
            @XmlAttribute(required = true)
            protected int order;
            @XmlAttribute(required = true)
            protected boolean isRequired;

            /**
             * Gets the value of the sourceElement property.
             * 
             * @return
             *     possible object is
             *     {@link Cure.Form.LinkElement.SourceElement }
             *     
             */
            public Cure.Form.LinkElement.SourceElement getSourceElement() {
                return sourceElement;
            }

            /**
             * Sets the value of the sourceElement property.
             * 
             * @param value
             *     allowed object is
             *     {@link Cure.Form.LinkElement.SourceElement }
             *     
             */
            public void setSourceElement(Cure.Form.LinkElement.SourceElement value) {
                this.sourceElement = value;
            }

            /**
             * Gets the value of the learnMore property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLearnMore() {
                return learnMore;
            }

            /**
             * Sets the value of the learnMore property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLearnMore(String value) {
                this.learnMore = value;
            }

            /**
             * Gets the value of the skipRule property.
             * 
             * @return
             *     possible object is
             *     {@link SkipRuleType }
             *     
             */
            public SkipRuleType getSkipRule() {
                return skipRule;
            }

            /**
             * Sets the value of the skipRule property.
             * 
             * @param value
             *     allowed object is
             *     {@link SkipRuleType }
             *     
             */
            public void setSkipRule(SkipRuleType value) {
                this.skipRule = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the uuid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUuid() {
                return uuid;
            }

            /**
             * Sets the value of the uuid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUuid(String value) {
                this.uuid = value;
            }

            /**
             * Gets the value of the order property.
             * 
             */
            public int getOrder() {
                return order;
            }

            /**
             * Sets the value of the order property.
             * 
             */
            public void setOrder(int value) {
                this.order = value;
            }

            /**
             * Gets the value of the isRequired property.
             * 
             */
            public boolean isIsRequired() {
                return isRequired;
            }

            /**
             * Sets the value of the isRequired property.
             * 
             */
            public void setIsRequired(boolean value) {
                this.isRequired = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice>
             *         &lt;element name="questionElement" type="{}questionElementType"/>
             *         &lt;element name="tableElement" type="{}tableElementType"/>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "questionElement",
                "tableElement"
            })
            public static class SourceElement {

                protected QuestionElementType questionElement;
                protected TableElementType tableElement;

                /**
                 * Gets the value of the questionElement property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link QuestionElementType }
                 *     
                 */
                public QuestionElementType getQuestionElement() {
                    return questionElement;
                }

                /**
                 * Sets the value of the questionElement property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link QuestionElementType }
                 *     
                 */
                public void setQuestionElement(QuestionElementType value) {
                    this.questionElement = value;
                }

                /**
                 * Gets the value of the tableElement property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TableElementType }
                 *     
                 */
                public TableElementType getTableElement() {
                    return tableElement;
                }

                /**
                 * Sets the value of the tableElement property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TableElementType }
                 *     
                 */
                public void setTableElement(TableElementType value) {
                    this.tableElement = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="section" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="skipRule" type="{}skipRuleType"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="moduleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="completionTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="showPleaseSelectOptionInDropDown" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="insertCheckAllThatApplyForMultiSelectAnswers" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *       &lt;attribute name="uuid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "section",
        "description",
        "moduleName",
        "completionTime",
        "showPleaseSelectOptionInDropDown",
        "insertCheckAllThatApplyForMultiSelectAnswers"
    })
    public static class Module {

        @XmlElement(required = true)
        protected List<Cure.Module.Section> section;
        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected String moduleName;
        @XmlElement(required = true)
        protected String completionTime;
        protected boolean showPleaseSelectOptionInDropDown;
        protected boolean insertCheckAllThatApplyForMultiSelectAnswers;
        @XmlAttribute(required = true)
        protected String uuid;

        /**
         * Gets the value of the section property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the section property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Cure.Module.Section }
         * 
         * 
         */
        public List<Cure.Module.Section> getSection() {
            if (section == null) {
                section = new ArrayList<Cure.Module.Section>();
            }
            return this.section;
        }

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the moduleName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModuleName() {
            return moduleName;
        }

        /**
         * Sets the value of the moduleName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModuleName(String value) {
            this.moduleName = value;
        }

        /**
         * Gets the value of the completionTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompletionTime() {
            return completionTime;
        }

        /**
         * Sets the value of the completionTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompletionTime(String value) {
            this.completionTime = value;
        }

        /**
         * Gets the value of the showPleaseSelectOptionInDropDown property.
         * 
         */
        public boolean isShowPleaseSelectOptionInDropDown() {
            return showPleaseSelectOptionInDropDown;
        }

        /**
         * Sets the value of the showPleaseSelectOptionInDropDown property.
         * 
         */
        public void setShowPleaseSelectOptionInDropDown(boolean value) {
            this.showPleaseSelectOptionInDropDown = value;
        }

        /**
         * Gets the value of the insertCheckAllThatApplyForMultiSelectAnswers property.
         * 
         */
        public boolean isInsertCheckAllThatApplyForMultiSelectAnswers() {
            return insertCheckAllThatApplyForMultiSelectAnswers;
        }

        /**
         * Sets the value of the insertCheckAllThatApplyForMultiSelectAnswers property.
         * 
         */
        public void setInsertCheckAllThatApplyForMultiSelectAnswers(boolean value) {
            this.insertCheckAllThatApplyForMultiSelectAnswers = value;
        }

        /**
         * Gets the value of the uuid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUuid() {
            return uuid;
        }

        /**
         * Sets the value of the uuid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUuid(String value) {
            this.uuid = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="skipRule" type="{}skipRuleType"/>
         *       &lt;/sequence>
         *       &lt;attribute name="order" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "skipRule"
        })
        public static class Section {

            @XmlElement(required = true)
            protected SkipRuleType skipRule;
            @XmlAttribute(required = true)
            protected int order;
            @XmlAttribute(required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object ref;

            /**
             * Gets the value of the skipRule property.
             * 
             * @return
             *     possible object is
             *     {@link SkipRuleType }
             *     
             */
            public SkipRuleType getSkipRule() {
                return skipRule;
            }

            /**
             * Sets the value of the skipRule property.
             * 
             * @param value
             *     allowed object is
             *     {@link SkipRuleType }
             *     
             */
            public void setSkipRule(SkipRuleType value) {
                this.skipRule = value;
            }

            /**
             * Gets the value of the order property.
             * 
             */
            public int getOrder() {
                return order;
            }

            /**
             * Sets the value of the order property.
             * 
             */
            public void setOrder(int value) {
                this.order = value;
            }

            /**
             * Gets the value of the ref property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getRef() {
                return ref;
            }

            /**
             * Sets the value of the ref property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setRef(Object value) {
                this.ref = value;
            }

        }

    }

}
