/*******************************************************************************
 * Copyright (c) 2012 HealthCare It, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the BSD 3-Clause license
 * which accompanies this distribution, and is available at
 * http://directory.fsf.org/wiki/License:BSD_3Clause
 * 
 * Contributors:
 *     HealthCare It, Inc - initial API and implementation
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.11 at 12:38:39 PM EDT 
//


package com.healthcit.cacure.export.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.healthcit.cacure.export.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.healthcit.cacure.export.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TableElementType }
     * 
     */
    public TableElementType createTableElementType() {
        return new TableElementType();
    }

    /**
     * Create an instance of {@link Cure.Form.ExternalQuestionElement }
     * 
     */
    public Cure.Form.ExternalQuestionElement createCureFormExternalQuestionElement() {
        return new Cure.Form.ExternalQuestionElement();
    }

    /**
     * Create an instance of {@link TableElementType.Question }
     * 
     */
    public TableElementType.Question createTableElementTypeQuestion() {
        return new TableElementType.Question();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link Cure.Form.LinkElement.SourceElement }
     * 
     */
    public Cure.Form.LinkElement.SourceElement createCureFormLinkElementSourceElement() {
        return new Cure.Form.LinkElement.SourceElement();
    }

    /**
     * Create an instance of {@link QuestionType.Answer }
     * 
     */
    public QuestionType.Answer createQuestionTypeAnswer() {
        return new QuestionType.Answer();
    }

    /**
     * Create an instance of {@link Cure.Form.Content }
     * 
     */
    public Cure.Form.Content createCureFormContent() {
        return new Cure.Form.Content();
    }

    /**
     * Create an instance of {@link SkipRuleType }
     * 
     */
    public SkipRuleType createSkipRuleType() {
        return new SkipRuleType();
    }

    /**
     * Create an instance of {@link Cure }
     * 
     */
    public Cure createCure() {
        return new Cure();
    }

    /**
     * Create an instance of {@link Cure.Form }
     * 
     */
    public Cure.Form createCureForm() {
        return new Cure.Form();
    }

    /**
     * Create an instance of {@link SkipRuleType.QuestionSkipRule }
     * 
     */
    public SkipRuleType.QuestionSkipRule createSkipRuleTypeQuestionSkipRule() {
        return new SkipRuleType.QuestionSkipRule();
    }

    /**
     * Create an instance of {@link Cure.Form.LinkElement }
     * 
     */
    public Cure.Form.LinkElement createCureFormLinkElement() {
        return new Cure.Form.LinkElement();
    }

    /**
     * Create an instance of {@link FormElementType.Categories.Category }
     * 
     */
    public FormElementType.Categories.Category createFormElementTypeCategoriesCategory() {
        return new FormElementType.Categories.Category();
    }

    /**
     * Create an instance of {@link SkipsType }
     * 
     */
    public SkipsType createSkipsType() {
        return new SkipsType();
    }

    /**
     * Create an instance of {@link Cure.Module.Section }
     * 
     */
    public Cure.Module.Section createCureModuleSection() {
        return new Cure.Module.Section();
    }

    /**
     * Create an instance of {@link QuestionType.Answer.AnswerValue }
     * 
     */
    public QuestionType.Answer.AnswerValue createQuestionTypeAnswerAnswerValue() {
        return new QuestionType.Answer.AnswerValue();
    }

    /**
     * Create an instance of {@link SkipRuleType.QuestionSkipRule.AnswerSkipRule }
     * 
     */
    public SkipRuleType.QuestionSkipRule.AnswerSkipRule createSkipRuleTypeQuestionSkipRuleAnswerSkipRule() {
        return new SkipRuleType.QuestionSkipRule.AnswerSkipRule();
    }

    /**
     * Create an instance of {@link FormElementType.Categories }
     * 
     */
    public FormElementType.Categories createFormElementTypeCategories() {
        return new FormElementType.Categories();
    }

    /**
     * Create an instance of {@link QuestionType }
     * 
     */
    public QuestionType createQuestionType() {
        return new QuestionType();
    }

    /**
     * Create an instance of {@link Cure.Module }
     * 
     */
    public Cure.Module createCureModule() {
        return new Cure.Module();
    }

    /**
     * Create an instance of {@link QuestionElementType }
     * 
     */
    public QuestionElementType createQuestionElementType() {
        return new QuestionElementType();
    }

    /**
     * Create an instance of {@link FormElementType }
     * 
     */
    public FormElementType createFormElementType() {
        return new FormElementType();
    }

}
